app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from app.views import (
    TaskListViews,
    TaskDetailViews,
    TaskCreationViews,
    TaskUpdateViews,
    TaskDeleteViews,
    complete_undo,
)

urlpatterns = [
    path("", TaskListViews.as_view(), name="task-list"),
    path("creation/", TaskCreationViews.as_view(), name="task-creation"),
    path("<int:pk>", TaskDetailViews.as_view(), name="task-detail"),
    path("<int:pk>/update", TaskUpdateViews.as_view(), name="task-update"),
    path("<int:pk>/delete", TaskDeleteViews.as_view(), name="task-delete"),
    path("<int:pk>/complete_undo", complete_undo, name="task-complete-undo")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "todo_list"

user/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views


urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "user"

ww_to_do_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("user.urls")),
    path("", include("app.urls", namespace="todolist"))
]

app/models.py
from django.db import models


class Task(models.Model):
    user = models.ForeignKey("user.User", on_delete=models.CASCADE, related_name="task")
    header = models.CharField(max_length=255)
    content = models.TextField()
    datetime = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done_or_not = models.BooleanField()

    class Meta:
        ordering = ["-datetime"]

user/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

app/forms.py
from django import forms
from django.forms import DateTimeInput

from app.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "user",
            "header",
            "content",
            "deadline",
            "done_or_not",
        ]
        exclude = ("user",)
        widgets = {
            "deadline": DateTimeInput(attrs={"placeholder": "Enter deadline like: 2022-12-25"}),
        }

app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect

from app.forms import TaskForm
from app.models import Task


class TaskListViews(generic.ListView):
    model = Task
    fields = "__all__"


class TaskDetailViews(generic.DetailView):
    model = Task
    fields = "__all__"


class TaskCreationViews(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todolist:task-list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TaskUpdateViews(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todolist:task-list")


class TaskDeleteViews(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todolist:task-list")


@login_required
def complete_undo(request, pk):
    task = Task.objects.get(pk=pk)
    task.done_or_not = not task.done_or_not
    task.save()
    next_url = request.GET.get("next")
    if next_url:
        return redirect(next_url)

user/views.py
from django.shortcuts import render

# Create your views here.

templates/app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/app/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ task.header }}</h1>
  <hr>
  Description:<h3>{{ task.content }}</h3>
  <hr>
  Created in:{{ task.datetime }}
  <p>
  Status: {% if task.done_or_not %}
      <strong style="color: green">Done</strong>
      <a href="{% url 'todolist:task-complete-undo' pk=task.pk %}?next={% url 'todolist:task-detail' pk=task.pk%}" class="btn btn-primary link-to-page">Undo</a>
      {% else %}
        <strong style="color: red"> Not done </strong>
      <a href="{% url 'todolist:task-complete-undo' pk=task.pk %}?next={% url 'todolist:task-detail' pk=task.pk%}" class="btn btn-success link-to-page">Complete</a>
    {% endif %}

  Deadline: {{ task.deadline }}
  </p>
{% endblock %}

templates/app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/app/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>
    TODO list
  <a href="{% url 'todolist:task-creation' %}" class="btn btn-primary link-to-page">Create</a>
  </h1>
  {% for task in task_list %}
    <hr>
    <p>
    {% if task.done_or_not %}
      <strong style="color: green">Done</strong>
      <a href="{% url 'todolist:task-complete-undo' pk=task.pk %}?next={% url 'todolist:task-list' %}" class="btn btn-primary link-to-page">Undo</a>
      {% else %}
        <strong style="color: red"> Not done </strong>
      <a href="{% url 'todolist:task-complete-undo' pk=task.pk %}?next={% url 'todolist:task-list' %}" class="btn btn-success link-to-page">Complete</a>
    {% endif %}
      <a href="{% url 'todolist:task-detail' pk=task.pk %}">{{ task.header }}</a>

    </p>
    <p>
      Created: {{ task.datetime }}
    </p>
    <p>
      <a href="{% url 'todolist:task-update' pk=task.pk %}">Update</a>
      <a href="{% url 'todolist:task-delete' pk=task.pk %}">Delete</a>
    </p>

  {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Todo list</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">

  {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>

</body>
</html>

templates/includes/sidebar.html
<ul>
  <li><a href="{% url 'todolist:task-list' %}">All task</a></li>

<li>
  {% if user.is_authenticated %}
    Hello: {{ user.username }}
    <a href="{% url 'user:logout' %}">Logout</a>
  {% else %}
    <a href="{% url 'user:login' %}">Login</a>
  {% endif %}
</li>

</ul>